# Generated by Django 4.2.3 on 2023-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20)),
                ('color_name', models.CharField(max_length=50)),
                ('product', models.ManyToManyField(to='clothes.product')),
            ],
        ),
    ]
