# Generated by Django 4.2.3 on 2023-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='product_category_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
