# Generated by Django 4.2.3 on 2023-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_productcategories_product_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='clothes.colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='product',
            field=models.ManyToManyField(related_name='product_colors', to='clothes.product'),
        ),
    ]
